package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"context"
	"errors"
	"padel-api/auth"
	"padel-api/graph/model"
)

// GetDashboardSummary is the resolver for the getDashboardSummary field.
func (r *queryResolver) GetDashboardSummary(ctx context.Context, input model.DashboardSummaryInput) (*model.DashboardSummary, error) {
	authUser := auth.GetAuthUser(ctx)
	if authUser.UserID == "" {
		return nil, errors.New("not authenticated")
	}

	return r.DashboardService.GetDashboardSummary(ctx, input)
}

// GetClubOverview is the resolver for the getClubOverview field.
func (r *queryResolver) GetClubOverview(ctx context.Context, input model.ClubOverviewInput) (*model.ClubOverviewResult, error) {
	authUser := auth.GetAuthUser(ctx)
	if authUser.UserID == "" {
		return nil, errors.New("not authenticated")
	}

	return r.DashboardService.GetClubOverview(ctx, input)
}

// GetLocations is the resolver for the getLocations field.
func (r *queryResolver) GetLocations(ctx context.Context) ([]*model.Location, error) {
	authUser := auth.GetAuthUser(ctx)
	if authUser.UserID == "" {
		return nil, errors.New("not authenticated")
	}

	return r.DashboardService.GetLocations(ctx)
}

// GetClubPerformanceAnalytics is the resolver for the getClubPerformanceAnalytics field.
func (r *queryResolver) GetClubPerformanceAnalytics(ctx context.Context, input model.ClubPerformanceAnalyticsInput) (*model.ClubPerformanceResult, error) {
	authUser := auth.GetAuthUser(ctx)
	if authUser.UserID == "" {
		return nil, errors.New("not authenticated")
	}

	return r.DashboardService.GetClubPerformanceAnalytics(ctx, input)
}

// GetBookingTrend is the resolver for the getBookingTrend field.
func (r *queryResolver) GetBookingTrend(ctx context.Context, filter model.AnalyticsFilter) ([]*model.AnalyticsChartItem, error) {
	authUser := auth.GetAuthUser(ctx)
	if authUser.UserID == "" {
		return nil, errors.New("not authenticated")
	}
	return r.DashboardService.GetBookingTrend(ctx, &filter)
}

// GetBookingsPerClub is the resolver for the getBookingsPerClub field.
func (r *queryResolver) GetBookingsPerClub(ctx context.Context, filter model.AnalyticsFilter, topX int) ([]*model.AnalyticsMultiSeries, error) {
	authUser := auth.GetAuthUser(ctx)
	if authUser.UserID == "" {
		return nil, errors.New("not authenticated")
	}
	return r.DashboardService.GetBookingsPerClub(ctx, &filter, topX)
}

// GetClubGrowthByCity is the resolver for the getClubGrowthByCity field.
func (r *queryResolver) GetClubGrowthByCity(ctx context.Context, filter model.AnalyticsFilter) ([]*model.AnalyticsMultiSeries, error) {
	authUser := auth.GetAuthUser(ctx)
	if authUser.UserID == "" {
		return nil, errors.New("not authenticated")
	}
	return r.DashboardService.GetClubGrowthByCity(ctx, &filter)
}

// GetCourtGrowthByCity is the resolver for the getCourtGrowthByCity field.
func (r *queryResolver) GetCourtGrowthByCity(ctx context.Context, filter model.AnalyticsFilter) ([]*model.AnalyticsMultiSeries, error) {
	authUser := auth.GetAuthUser(ctx)
	if authUser.UserID == "" {
		return nil, errors.New("not authenticated")
	}
	return r.DashboardService.GetCourtGrowthByCity(ctx, &filter)
}

// GetBookingDistribution is the resolver for the getBookingDistribution field.
func (r *queryResolver) GetBookingDistribution(ctx context.Context, filter model.AnalyticsFilter, topX int) ([]*model.AnalyticsPieItem, error) {
	authUser := auth.GetAuthUser(ctx)
	if authUser.UserID == "" {
		return nil, errors.New("not authenticated")
	}
	return r.DashboardService.GetBookingDistribution(ctx, &filter, topX)
}

// GetClubsPerCity is the resolver for the getClubsPerCity field.
func (r *queryResolver) GetClubsPerCity(ctx context.Context, filter model.AnalyticsFilter) ([]*model.AnalyticsPieItem, error) {
	authUser := auth.GetAuthUser(ctx)
	if authUser.UserID == "" {
		return nil, errors.New("not authenticated")
	}
	return r.DashboardService.GetClubsPerCity(ctx, &filter)
}

// GetPriceDistribution is the resolver for the getPriceDistribution field.
func (r *queryResolver) GetPriceDistribution(ctx context.Context, filter model.AnalyticsFilter) ([]*model.AnalyticsPieItem, error) {
	authUser := auth.GetAuthUser(ctx)
	if authUser.UserID == "" {
		return nil, errors.New("not authenticated")
	}
	return r.DashboardService.GetPriceDistribution(ctx, &filter)
}

// GetCourtDistribution is the resolver for the getCourtDistribution field.
func (r *queryResolver) GetCourtDistribution(ctx context.Context, filter model.AnalyticsFilter) ([]*model.AnalyticsPieItem, error) {
	authUser := auth.GetAuthUser(ctx)
	if authUser.UserID == "" {
		return nil, errors.New("not authenticated")
	}
	return r.DashboardService.GetCourtDistribution(ctx, &filter)
}

// GetAnalyticsSummary is the resolver for the getAnalyticsSummary field.
func (r *queryResolver) GetAnalyticsSummary(ctx context.Context, filter model.AnalyticsFilter) (*model.DashboardSummary, error) {
	authUser := auth.GetAuthUser(ctx)
	if authUser.UserID == "" {
		return nil, errors.New("not authenticated")
	}
	return r.DashboardService.GetAnalyticsSummary(ctx, &filter)
}
