package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"context"
	"errors"
	"padel-api/auth"
	"padel-api/graph/model"
)

// Clubs is the resolver for the clubs field.
func (r *queryResolver) Clubs(ctx context.Context, input model.ClubsInput) (*model.ClubsResult, error) {
	authUser := auth.GetAuthUser(ctx)
	if authUser.UserID == "" {
		return nil, errors.New("not authenticated")
	}

	return r.ClubService.GetClubs(input)
}

// Club is the resolver for the club field.
func (r *queryResolver) Club(ctx context.Context, id string) (*model.Club, error) {
	return r.ClubService.GetByID(id)
}
