package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"context"
	"database/sql"
	"errors"
	"log"
	"padel-api/auth"
	"padel-api/graph/model"
)

// Authenticate is the resolver for the authenticate field.
func (r *mutationResolver) Authenticate(ctx context.Context, userid string, password string) (*model.AuthPayload, error) {
	payload, err := r.UserService.Authenticate(userid, password)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, errors.New("invalid credentials")
		}
		log.Printf("[AUTH] Authenticate error: %v", err)
		return nil, errors.New("authentication failed")
	}
	return payload, nil
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context, refreshToken string) (*model.AuthPayload, error) {
	log.Printf("[AUTH] RefreshToken called, token length=%d", len(refreshToken))
	payload, err := r.UserService.RefreshToken(refreshToken)
	if err != nil {
		log.Printf("[AUTH] RefreshToken error: %v", err)
		return nil, errors.New("invalid or expired refresh token")
	}
	log.Printf("[AUTH] RefreshToken success: user=%s newTokenLen=%d", payload.User.Userid, len(payload.Token))
	return payload, nil
}

// RevokeToken is the resolver for the revokeToken field.
func (r *mutationResolver) RevokeToken(ctx context.Context, refreshToken string) (bool, error) {
	return true, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	authUser := auth.GetAuthUser(ctx)
	if authUser.UserID == "" {
		return nil, errors.New("not authenticated")
	}

	user, err := r.UserService.GetByID(authUser.UserID)
	if err != nil {
		return nil, errors.New("user not found")
	}
	return user, nil
}
