# Database Configuration
DB_HOST=34.101.246.70
DB_PORT=5432
DB_USER=padelitics
DB_PASSWORD=P@del1tic5
DB_NAME=padelitics
DB_SSL_MODE=disable

COURTSIDE_EMAIL=kucaricintaku@gmail.com
COURTSIDE_PASSWORD=caricinta83

# JWT Secret Key
JWT_SECRET_KEY=padel-api-secret-key-change-in-production
ALLOWED_ORIGINS=http://localhost:8000

# Server
PORT=8080