// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type AnalyticsChartItem struct {
	Label string  `json:"label"`
	Value float64 `json:"value"`
}

type AnalyticsFilter struct {
	LocationID    *string  `json:"locationId,omitempty"`
	From          *string  `json:"from,omitempty"`
	To            *string  `json:"to,omitempty"`
	MinCourtCount *int     `json:"minCourtCount,omitempty"`
	MaxCourtCount *int     `json:"maxCourtCount,omitempty"`
	MinPrice      *float64 `json:"minPrice,omitempty"`
	MaxPrice      *float64 `json:"maxPrice,omitempty"`
}

type AnalyticsMultiSeries struct {
	Label  string                 `json:"label"`
	Series []*AnalyticsSeriesItem `json:"series"`
}

type AnalyticsPieItem struct {
	Name  string  `json:"name"`
	Value float64 `json:"value"`
}

type AnalyticsSeriesItem struct {
	Name  string  `json:"name"`
	Value float64 `json:"value"`
}

type AuthPayload struct {
	User         *User  `json:"user"`
	Token        string `json:"token"`
	RefreshToken string `json:"refreshToken"`
	ExpiresIn    int    `json:"expiresIn"`
}

type Club struct {
	ID           string         `json:"id"`
	Name         string         `json:"name"`
	SubName      *string        `json:"subName,omitempty"`
	Address      *string        `json:"address,omitempty"`
	Email        *string        `json:"email,omitempty"`
	Whatsapp     *string        `json:"whatsapp,omitempty"`
	Instagram    *string        `json:"instagram,omitempty"`
	LogoPath     *string        `json:"logoPath,omitempty"`
	Lat          *float64       `json:"lat,omitempty"`
	Lng          *float64       `json:"lng,omitempty"`
	LinkMap      *string        `json:"linkMap,omitempty"`
	OpeningHours map[string]any `json:"openingHours,omitempty"`
	OpeningDate  *time.Time     `json:"openingDate,omitempty"`
	LocationID   string         `json:"locationId"`
	Price        *float64       `json:"price,omitempty"`
	CourtCount   *int           `json:"courtCount,omitempty"`
}

type ClubOccupancyDayRow struct {
	Day   string               `json:"day"`
	Slots []*ClubOccupancySlot `json:"slots"`
}

type ClubOccupancySlot struct {
	Time          string  `json:"time"`
	OccupancyRate float64 `json:"occupancyRate"`
}

type ClubOverviewInput struct {
	LocationID    *string  `json:"locationId,omitempty"`
	From          *string  `json:"from,omitempty"`
	To            *string  `json:"to,omitempty"`
	SortField     *string  `json:"sortField,omitempty"`
	SortOrder     *string  `json:"sortOrder,omitempty"`
	Page          int      `json:"page"`
	PageSize      int      `json:"pageSize"`
	MinCourtCount *int     `json:"minCourtCount,omitempty"`
	MaxCourtCount *int     `json:"maxCourtCount,omitempty"`
	MinPrice      *float64 `json:"minPrice,omitempty"`
	MaxPrice      *float64 `json:"maxPrice,omitempty"`
}

type ClubOverviewItem struct {
	ID           string   `json:"id"`
	Name         string   `json:"name"`
	SubName      *string  `json:"subName,omitempty"`
	Address      *string  `json:"address,omitempty"`
	Lat          *float64 `json:"lat,omitempty"`
	Lng          *float64 `json:"lng,omitempty"`
	LocationID   string   `json:"locationId"`
	LogoPath     *string  `json:"logoPath,omitempty"`
	Price        *float64 `json:"price,omitempty"`
	BookingCount int      `json:"bookingCount"`
	TotalRevenue float64  `json:"totalRevenue"`
}

type ClubOverviewResult struct {
	Items       []*ClubOverviewItem `json:"items"`
	TotalCount  int                 `json:"totalCount"`
	TotalPages  int                 `json:"totalPages"`
	HasNextPage bool                `json:"hasNextPage"`
}

type ClubPerformanceAnalyticsInput struct {
	ClubID string `json:"clubId"`
	From   string `json:"from"`
	To     string `json:"to"`
}

type ClubPerformanceChartItem struct {
	Label string  `json:"label"`
	Value float64 `json:"value"`
}

type ClubPerformanceMetrics struct {
	TotalBookings    int     `json:"totalBookings"`
	AvgDailyBookings float64 `json:"avgDailyBookings"`
	TotalRevenue     float64 `json:"totalRevenue"`
	AvgDailyRevenue  float64 `json:"avgDailyRevenue"`
}

type ClubPerformanceResult struct {
	Metrics          *ClubPerformanceMetrics     `json:"metrics"`
	BookingChart     []*ClubPerformanceChartItem `json:"bookingChart"`
	RevenueChart     []*ClubPerformanceChartItem `json:"revenueChart"`
	OccupancyHeatmap []*ClubOccupancyDayRow      `json:"occupancyHeatmap"`
	PriceMap         []*ClubPriceDayRow          `json:"priceMap"`
}

type ClubPriceDayRow struct {
	Day   string           `json:"day"`
	Slots []*ClubPriceSlot `json:"slots"`
}

type ClubPriceSlot struct {
	Time  string  `json:"time"`
	Price float64 `json:"price"`
}

type ClubsInput struct {
	Page              int      `json:"page"`
	PageSize          int      `json:"pageSize"`
	LocationID        *string  `json:"locationId,omitempty"`
	Search            *string  `json:"search,omitempty"`
	SortField         *string  `json:"sortField,omitempty"`
	SortOrder         *string  `json:"sortOrder,omitempty"`
	MinCourtCount     *int     `json:"minCourtCount,omitempty"`
	MaxCourtCount     *int     `json:"maxCourtCount,omitempty"`
	MinPrice          *float64 `json:"minPrice,omitempty"`
	MaxPrice          *float64 `json:"maxPrice,omitempty"`
	OpeningDateBefore *string  `json:"openingDateBefore,omitempty"`
	OpeningDateAfter  *string  `json:"openingDateAfter,omitempty"`
}

type ClubsResult struct {
	Clubs       []*Club `json:"clubs"`
	TotalCount  int     `json:"totalCount"`
	TotalPages  int     `json:"totalPages"`
	HasNextPage bool    `json:"hasNextPage"`
}

type DashboardSummary struct {
	TotalClubs    int     `json:"totalClubs"`
	TotalBookings int     `json:"totalBookings"`
	TotalRevenue  float64 `json:"totalRevenue"`
	LastUpdatedAt *string `json:"lastUpdatedAt,omitempty"`
}

type DashboardSummaryInput struct {
	LocationID    *string  `json:"locationId,omitempty"`
	From          *string  `json:"from,omitempty"`
	To            *string  `json:"to,omitempty"`
	MinCourtCount *int     `json:"minCourtCount,omitempty"`
	MaxCourtCount *int     `json:"maxCourtCount,omitempty"`
	MinPrice      *float64 `json:"minPrice,omitempty"`
	MaxPrice      *float64 `json:"maxPrice,omitempty"`
}

type Location struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Mutation struct {
}

type Query struct {
}

type User struct {
	ID     string `json:"id"`
	Name   string `json:"name"`
	Email  string `json:"email"`
	Userid string `json:"userid"`
	Status string `json:"status"`
}
