# Database Configuration (Production Example)
DB_HOST=34.101.246.70
DB_PORT=5432
DB_USER=padelitics
DB_PASSWORD=P@del1tic5
DB_NAME=padelitics
DB_SSL_MODE=disable

COURTSIDE_EMAIL=kucaricintaku@gmail.com
COURTSIDE_PASSWORD=caricinta83

LOCATIONS=9eabec1b-e9c9-4f67-b9f5-f99c063a1a35